# Generated by Django 5.1.2 on 2026-04-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate Limited')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='chatbot_cha_timesta_1c0f18_idx'), models.Index(fields=['status'], name='chatbot_cha_status_3b463c_idx'), models.Index(fields=['user_identifier'], name='chatbot_cha_user_id_46a186_idx')],
            },
        ),
    ]
