# Generated by Django 5.1.2 on 2026-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='medical_docs/'),
        ),
    ]
